#!/usr/bin/env bash
# Configure custom IPv4 mappings for localhost and facebook.com.
sed -i '/[[:space:]]localhost\([[:space:]]\|$\)/d' /etc/hosts
sed -i '/[[:space:]]facebook\.com\([[:space:]]\|$\)/d' /etc/hosts
printf '127.0.0.2 localhost\n8.8.8.8 facebook.com\n' >> /etc/hosts
