#!/usr/bin/env bash
# Configure custom IPv4 mappings for localhost and facebook.com.
hosts_file=$(mktemp)
sed -e '/[[:space:]]localhost\([[:space:]]\|$\)/d' \
    -e '/[[:space:]]facebook\.com\([[:space:]]\|$\)/d' /etc/hosts > "$hosts_file"
printf '127.0.0.2 localhost\n8.8.8.8 facebook.com\n' >> "$hosts_file"
cat "$hosts_file" > /etc/hosts
rm -f "$hosts_file"
